import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class ComplaintPdfGenerator {
  static Future<void> generateAndDownload({
    required List<Map<String, dynamic>> complaints,
    // Parameters kept for compatibility, but UI buttons are removed as requested
    required int total,
    required int resolved,
    required int pending,
    required int urgent,
  }) async {
    final pdf = pw.Document();

    // Load College Logo from the specified path
    pw.MemoryImage? logoImage;
    try {
      // Ensure this matches the exact path in your pubspec.yaml
      final bytes = await rootBundle.load('assets/gpcslogo.png');
      logoImage = pw.MemoryImage(bytes.buffer.asUint8List());
    } catch (e) {
      // If logo fails to load, the header will still align properly without it
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(35),
        header: (pw.Context context) => _buildProfessionalHeader(logoImage),
        footer: (pw.Context context) => _buildCreativeFooter(context),
        build: (pw.Context context) => [
          pw.SizedBox(height: 20),

          pw.Text(
            "Detailed Complaint Management Records",
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey900),
          ),
          pw.SizedBox(height: 15),

          // PROFESSIONAL DATA TABLE
          pw.TableHelper.fromTextArray(
            headers: ["#", "Category & Description", "Room", "Urgency", "Status"],
            data: List<List<dynamic>>.generate(
              complaints.length,
                  (index) {
                final c = complaints[index];
                return [
                  (index + 1).toString(),
                  "${c['category'] ?? "General"}\n${c['description'] ?? "N/A"}",
                  c['roomNo'] ?? "---",
                  c['urgency'] ?? "Low",
                  c['status']?.toUpperCase() ?? "PENDING",
                ];
              },
            ),
            headerStyle: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold, fontSize: 10),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey800),
            cellHeight: 35,
            cellStyle: const pw.TextStyle(fontSize: 9),
            columnWidths: {
              0: const pw.FixedColumnWidth(25),
              1: const pw.FlexColumnWidth(),
              2: const pw.FixedColumnWidth(50),
              3: const pw.FixedColumnWidth(60),
              4: const pw.FixedColumnWidth(70),
            },
            cellAlignment: pw.Alignment.centerLeft,
            cellAlignments: {
              0: pw.Alignment.center,
              2: pw.Alignment.center,
              3: pw.Alignment.center,
              4: pw.Alignment.center,
            },
            // Striped row decoration
            oddRowDecoration: const pw.BoxDecoration(color: PdfColors.grey50),
            border: pw.TableBorder.all(color: PdfColors.grey200, width: 0.5),
          ),
        ],
      ),
    );

    // Triggers the system print/save dialog
    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }

  // UPDATED HEADER: Logo on Top Left with College Branding
  static pw.Widget _buildProfessionalHeader(pw.MemoryImage? logo) {
    return pw.Column(
      children: [
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            if (logo != null) pw.Image(logo, width: 60),
            pw.SizedBox(width: 20),
            pw.Expanded(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text("GOVERNMENT POLYTECHNIC, CHHATRAPATI SAMBHAJINAGAR",
                      style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 13, color: PdfColors.black)),
                  pw.Text("BOYS HOSTEL PORTAL",
                      style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 12, color: PdfColors.blue800)),
                  pw.Text("Online Academic Management System",
                      style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700)),
                ],
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 10),
        pw.Divider(thickness: 1.5, color: PdfColors.blueGrey100),
      ],
    );
  }

  // UPDATED FOOTER: Professional Bottom Bar
  static pw.Widget _buildCreativeFooter(pw.Context context) {
    final dateStr = DateFormat('dd MMM yyyy, hh:mm a').format(DateTime.now());
    return pw.Column(
      children: [
        pw.Divider(thickness: 1, color: PdfColors.grey300),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text("Auto-generated by GPCH Hostel Portal",
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
            pw.Text("Generated on: $dateStr",
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
            pw.Text("Page ${context.pageNumber} of ${context.pagesCount}",
                style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600)),
          ],
        ),
        pw.SizedBox(height: 10),
        // PROFESSIONAL CONTACT STRIP
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 10),
          decoration: const pw.BoxDecoration(color: PdfColors.grey100),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
            children: [
              pw.Text("Web: www.gpch.edu.in", style: const pw.TextStyle(fontSize: 8, color: PdfColors.blueGrey800)),
              pw.Text("Email: info@gpch.edu.in", style: const pw.TextStyle(fontSize: 8, color: PdfColors.blueGrey800)),
              pw.Text("Location: Sambhajinagar, MH", style: const pw.TextStyle(fontSize: 8, color: PdfColors.blueGrey800)),
            ],
          ),
        ),
      ],
    );
  }
}