// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxqeEgim9roQiykTzAAeYf8J79G7_MOzk',
    appId: '1:979674054918:web:889e5533adcf8a0e0f9e87',
    messagingSenderId: '979674054918',
    projectId: 'gpcs-hostel-portal',
    authDomain: 'gpcs-hostel-portal.firebaseapp.com',
    storageBucket: 'gpcs-hostel-portal.firebasestorage.app',
    measurementId: 'G-0GVWT3PEEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK6OQ4Kj67LGZe1715WE6qsoDSaoueJ94',
    appId: '1:979674054918:android:0ed0095895c30b0e0f9e87',
    messagingSenderId: '979674054918',
    projectId: 'gpcs-hostel-portal',
    storageBucket: 'gpcs-hostel-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZVToknRNEZeeLkVh6vg7feywOxmUBEfQ',
    appId: '1:979674054918:ios:3dfb163d3faef6170f9e87',
    messagingSenderId: '979674054918',
    projectId: 'gpcs-hostel-portal',
    storageBucket: 'gpcs-hostel-portal.firebasestorage.app',
    iosBundleId: 'com.example.gpcsHostelPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZVToknRNEZeeLkVh6vg7feywOxmUBEfQ',
    appId: '1:979674054918:ios:3dfb163d3faef6170f9e87',
    messagingSenderId: '979674054918',
    projectId: 'gpcs-hostel-portal',
    storageBucket: 'gpcs-hostel-portal.firebasestorage.app',
    iosBundleId: 'com.example.gpcsHostelPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxqeEgim9roQiykTzAAeYf8J79G7_MOzk',
    appId: '1:979674054918:web:acf7e8dda3e1e54b0f9e87',
    messagingSenderId: '979674054918',
    projectId: 'gpcs-hostel-portal',
    authDomain: 'gpcs-hostel-portal.firebaseapp.com',
    storageBucket: 'gpcs-hostel-portal.firebasestorage.app',
    measurementId: 'G-H45KLWNCS4',
  );
}
